version: '3.8'

services:
  mockserver:
    image: mockserver/mockserver:latest
    container_name: mockserver
    ports:
      - "1080:1080"
      - "1090:1090"
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/mockserver-config.json
    volumes:
      - ./local/config:/config

  redis:
    image: "redis:latest"
    container_name: "redis-server"  # Nome do contêiner
    ports:
      - "6379:6379"
    volumes:
      - ./local/redis-data:/data

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'

